### ISSUE TITLE
哥 能刷资源的吗  惨遭老师毒害

### ISSUE THREAD

**Issue by zsjlovestudy** [congyewang/Lanmoyun_download#3]
一门课，蓝墨云上六个课程，一门课程蓝墨云5000多个资源。
我菜鸡一个搞不来

**Comment by congyewang** [comment]
刷新啥资源，能举个具体点的例子吗？

**Comment by congyewang** [comment]
> 一门课，蓝墨云上六个课程，一门课程蓝墨云5000多个资源。
> 我菜鸡一个搞不来

刷新啥资源，能给个具体例子吗？

**Comment by congyewang** [comment]
> 一门课，蓝墨云上六个课程，一门课程蓝墨云5000多个资源。
> 我菜鸡一个搞不来
你要是有答案库可以。给你思路吧，xpath上批量提取题目放在list里，然后和你的答案库进行比对。或者是用搜索引擎的api先搜索结果，再通过分词技术选择答案里最相似的。答案库这个工作量太大了，我做不了。
如果不考虑正确率，直接写javascript脚本就好，不需要python
以下为参考代码
```javascript
answer_list = document.getElementsByTagName("i")
for(i=0;i<answer_list.length;i++) {test[i].click()}
```
