### ISSUE TITLE
2020/3/18

### ISSUE THREAD

**Issue by lmh77** [congyewang/Lanmoyun_download#4]
请问还能不能使用

**Comment by congyewang** [comment]
可以啊

**Comment by congyewang** [comment]
> 请问还能不能使用

可以啊

**Comment by congyewang** [comment]
> 请问还能不能使用

可以啊，但是建议不要直接用编译好的文件，直接用源码。因为我的电脑是Mac，win直接用可能有兼容性问题。

**Comment by lmh77** [comment]
> > 请问还能不能使用
> 
> 
> 
> 可以啊，但是建议不要直接用编译好的文件，直接用源码。因为我的电脑是Mac，win直接用可能有兼容性问题。

我爬到空白，文件确实创建出来了

**Comment by congyewang** [comment]
> > > 请问还能不能使用
> > 
> > 
> > 可以啊，但是建议不要直接用编译好的文件，直接用源码。因为我的电脑是Mac，win直接用可能有兼容性问题。
> 
> 我爬到空白，文件确实创建出来了

有报错吗？

**Comment by lmh77** [comment]
> > > > 请问还能不能使用
> 
> > > 
> 
> > > 
> 
> > > 可以啊，但是建议不要直接用编译好的文件，直接用源码。因为我的电脑是Mac，win直接用可能有兼容性问题。
> 
> > 
> 
> > 我爬到空白，文件确实创建出来了
> 
> 
> 
> 有报错吗？

好像有，前段时间试的，方便留个微信吗

**Comment by congyewang** [comment]
> > > > > 请问还能不能使用
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > 可以啊，但是建议不要直接用编译好的文件，直接用源码。因为我的电脑是Mac，win直接用可能有兼容性问题。
> > 
> > 
> > > 
> > 
> > 
> > > 我爬到空白，文件确实创建出来了
> > 
> > 
> > 有报错吗？
> 
> 好像有，前段时间试的，方便留个微信吗

可以，待会儿给你发邮件吧

**Comment by lmh77** [comment]
> > > > > > 请问还能不能使用
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > 可以啊，但是建议不要直接用编译好的文件，直接用源码。因为我的电脑是Mac，win直接用可能有兼容性问题。
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > 我爬到空白，文件确实创建出来了
> 
> > > 
> 
> > > 
> 
> > > 有报错吗？
> 
> > 
> 
> > 好像有，前段时间试的，方便留个微信吗
> 
> 
> 
> 可以，待会儿给你发邮件吧

要不你重新发一下份源码到我邮箱，873397346@qq.com

**Comment by lmh77** [comment]
> > > > > > 请问还能不能使用
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > 可以啊，但是建议不要直接用编译好的文件，直接用源码。因为我的电脑是Mac，win直接用可能有兼容性问题。
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > 我爬到空白，文件确实创建出来了
> 
> > > 
> 
> > > 
> 
> > > 有报错吗？
> 
> > 
> 
> > 好像有，前段时间试的，方便留个微信吗
> 
> 
> 
> 可以，待会儿给你发邮件吧

刚才试了一下，没用Lanmoyun_scrapy文件夹内的，运行data.py输完账号密码和链接以后，读取到17份，其中只有3个是测试，连测试外的活动也读取，然后进度条跑完以后，Sum.txt内没有内容，运行过程也没有报错

**Comment by congyewang** [comment]
> > > > > > > 请问还能不能使用
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > 可以啊，但是建议不要直接用编译好的文件，直接用源码。因为我的电脑是Mac，win直接用可能有兼容性问题。
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > 我爬到空白，文件确实创建出来了
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > 有报错吗？
> > 
> > 
> > > 
> > 
> > 
> > > 好像有，前段时间试的，方便留个微信吗
> > 
> > 
> > 可以，待会儿给你发邮件吧
> 
> 刚才试了一下，没用Lanmoyun_scrapy文件夹内的，运行data.py输完账号密码和链接以后，读取到17份，其中只有3个是测试，连测试外的活动也读取，然后进度条跑完以后，Sum.txt内没有内容，运行过程也没有报错

1. 关于测试外的活动。我没有写判断来删掉这部分，因为我们老师当年不发活动，所以具体我不知道标准是什么。你可以在源码中改一下，再建一个你自己的分支然后push，我测试通过后给你merge进来。如果活动有明显特点的话应该不是很难改。

2. 关于Sum.txt内没有内容。依据经验判断读写问题与权限有关，这个除非给我准确的报错信息，否则我无法复现此Bug。2020年4月2日又分别在Mac上和Win7上重新测试了下，程序运行良好。如果存在问题请尝试右键后以管理员身份运行。或自行在程序同级目录建立`Sum.txt`文件。

**Comment by lmh77** [comment]
> > > > > > > > 请问还能不能使用
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > > 可以啊，但是建议不要直接用编译好的文件，直接用源码。因为我的电脑是Mac，win直接用可能有兼容性问题。
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > 我爬到空白，文件确实创建出来了
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > 有报错吗？
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > 好像有，前段时间试的，方便留个微信吗
> 
> > > 
> 
> > > 
> 
> > > 可以，待会儿给你发邮件吧
> 
> > 
> 
> > 刚才试了一下，没用Lanmoyun_scrapy文件夹内的，运行data.py输完账号密码和链接以后，读取到17份，其中只有3个是测试，连测试外的活动也读取，然后进度条跑完以后，Sum.txt内没有内容，运行过程也没有报错
> 
> 
> 
> 1. 关于测试外的活动。我没有写判断来删掉这部分，因为我们老师当年不发活动，所以具体我不知道标准是什么。你可以在源码中改一下，再建一个你自己的分支然后push，我测试通过后给你merge进来。如果活动有明显特点的话应该不是很难改。
> 
> 
> 
> 2. 关于Sum.txt内没有内容。依据经验判断读写问题与权限有关，这个除非给我准确的报错信息，否则我无法复现此Bug。2020年4月2日又分别在Mac上和Win7上重新测试了下，程序运行良好。如果存在问题请尝试右键后以管理员身份运行。或自行在程序同级目录建立`Sum.txt`文件。

非常感谢，太给力了，以管理员身份运行打包好的exe，有内容了，但是好像题目不全，等下次发布新测试活动再试试

**Comment by congyewang** [comment]
> > > > > > > > > 请问还能不能使用
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > > > 可以啊，但是建议不要直接用编译好的文件，直接用源码。因为我的电脑是Mac，win直接用可能有兼容性问题。
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > > 我爬到空白，文件确实创建出来了
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > 有报错吗？
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > 好像有，前段时间试的，方便留个微信吗
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > 可以，待会儿给你发邮件吧
> > 
> > 
> > > 
> > 
> > 
> > > 刚才试了一下，没用Lanmoyun_scrapy文件夹内的，运行data.py输完账号密码和链接以后，读取到17份，其中只有3个是测试，连测试外的活动也读取，然后进度条跑完以后，Sum.txt内没有内容，运行过程也没有报错
> > 
> > 
> > 
> > 1. 关于测试外的活动。我没有写判断来删掉这部分，因为我们老师当年不发活动，所以具体我不知道标准是什么。你可以在源码中改一下，再建一个你自己的分支然后push，我测试通过后给你merge进来。如果活动有明显特点的话应该不是很难改。
> > 2. 关于Sum.txt内没有内容。依据经验判断读写问题与权限有关，这个除非给我准确的报错信息，否则我无法复现此Bug。2020年4月2日又分别在Mac上和Win7上重新测试了下，程序运行良好。如果存在问题请尝试右键后以管理员身份运行。或自行在程序同级目录建立`Sum.txt`文件。
> 
> 非常感谢，太给力了，以管理员身份运行打包好的exe，有内容了，但是好像题目不全，等下次发布新测试活动再试试

好的，那我就把Bug标签取消了。
