### ISSUE TITLE
请问一下爬取题目的功能失效了吗

### ISSUE THREAD

**Issue by SummonHIM** [congyewang/Lanmoyun_download#5]
爬取虽然没有提示错误但是爬取的内容有残缺

**Comment by SummonHIM** [comment]
clazz_course_id我打码了

**Comment by congyewang** [comment]
> 爬取虽然没有提示错误但是爬取的内容有残缺

具体的情况可以截图吗？或者是有详细的对比，可以运行`diff <正常文件> <Scrapy残缺文件>`截取详细结果我看下。因为在2020年4月2日的测试中两种方案生成的文件MD5值相同，所以我认为在当天运行时Scrapy爬取结果没有残缺。

**Comment by SummonHIM** [comment]
我在我创建的班课里测试是有效的
但是在我老师的班课里却只爬出投票的活动
![批注 2020-04-09 150823](https://user-images.githubusercontent.com/33192611/78867782-43c4fe00-7a74-11ea-8aba-69d234e576ff.png)
![批注 2020-04-09 150805](https://user-images.githubusercontent.com/33192611/78867784-44f62b00-7a74-11ea-89aa-32834b22b656.png)

**Comment by congyewang** [comment]
> 我在我创建的班课里测试是有效的
> 但是在我老师的班课里却只爬出投票的活动

好的，那么您能说一下您的班课和老师的班课在网址或者是其他方面的不同吗？比如有User-Agent的反爬检测、Cookie的更改、网页结构有变化导致Xpath有变化等。

如果不能复现，那么我很难保证这是个共性的Bug。因为我测试的时候没有发生这种情况，而且您在运行过程中没有返回错误代码，这就意味着与网络或运行方式无关。

所以我不能确定我的程序是否出现了问题，并且不太清楚如何进行修复。

您可以用README中写出的**开发者工具**对您老师页面中您需要爬取的Xpath进行分析，或粘贴Xpath在本issue中提交。

还有种可能是您的老师没有放开蓝墨云中查看题目答案的权限，导致您在提交后并不能返回题目查看页面。请确保您可以人工进入此页面。

**Comment by SummonHIM** [comment]
我把title的Xpath改成如下之后
```
/html/body/div[@id='cc-main']/div[2]/div[4]/div[@class='view-quiz-row'][1]/div[@class='row-center']/div[@class='topic-options']/div[1]/div[@class='view-quiz-subject']/div[3]/pre[@class='color-33` topic-subject']
```
就可以爬取选项和答案了
但是标题却一直显示<Element pre at 0xOOOOOOOOOOO>

**Comment by SummonHIM** [comment]
后面添加了`/text()`后
```
/html/body/div[@id='cc-main']/div[2]/div[4]/div[@class='view-quiz-row'][1]/div[@class='row-center']/div[@class='topic-options']/div[1]/div[@class='view-quiz-subject']/div[3]/pre[@class='color-33` topic-subject']/text()
```
又不能正常爬取了

**Comment by congyewang** [comment]
> 后面添加了`/text()`后
> 
> ```
> /html/body/div[@id='cc-main']/div[2]/div[4]/div[@class='view-quiz-row'][1]/div[@class='row-center']/div[@class='topic-options']/div[1]/div[@class='view-quiz-subject']/div[3]/pre[@class='color-33` topic-subject']/text()
> ```
> 
> 又不能正常爬取了

请尝试修改为`//pre[@class="color-33 topic-subject"]/text()`

**Comment by SummonHIM** [comment]
我知道了
我尝试在xpath后面添加了个print把title，ans_sum，curr都print了出来
发现是可以正常爬取的
```
try:
            for i in range(len(html.xpath('/html/body/div[3]/div[2]/div[4]/div'))):
                title.append(html.xpath(
                    f"/html/body/div[@id='cc-main']/div[2]/div[4]/div[@class='view-quiz-row'][{i + 1}]/div[@class='row-center']/div[@class='topic-options']/div[1]/div[@class='view-quiz-subject']/div[3]//pre[@class='color-33 topic-subject']/text()"))
                ans = []
                for j in range(len(html.xpath(f"/html/body/div[@id='cc-main']/div[2]/div[4]/div[@class='view-quiz-row'][{i + 1}]/div[@class='row-center']/div[@class='topic-options']/div[@class='view-topic-options']/div[@class='option-content']"))):
                    ans.append(html.xpath(
                        f"/html/body/div[@id='cc-main']/div[2]/div[4]/div[@class='view-quiz-row'][{i + 1}]/div[@class='row-center']/div[@class='topic-options']/div[@class='view-topic-options']/div[@class='option-content'][{j + 1}]//span[@class='person-result-answer']/text()"))
                ans_sum.append(ans)
                curr.append(html.xpath(
                    f"/html/body/div[@id='cc-main']/div[2]/div[4]/div[@class='view-quiz-row'][{i + 1}]/div[@class='true-rate']/div[1]/div[@class='answer-box'][1]//span/text()"))
        except Exception:
            pass
        print(title)
        print(ans_sum)
        print(curr)
        return title, ans_sum, curr
```
我们老师喜欢在题目里面加(  )
在控制台中输出的空格就全部都转换为` \xa0 `了
可能原因出在这里吧
![批注 2020-04-10 090353](https://user-images.githubusercontent.com/33192611/78953082-42deab80-7b0a-11ea-98c1-131cc120d63d.png)

**Comment by SummonHIM** [comment]
我在我自己的版课上测试也是如此
似乎只要列表中有一个空格就无法输出
##### 两道题目
---
![web1](https://user-images.githubusercontent.com/33192611/78953839-af5aaa00-7b0c-11ea-877d-c8a2946df502.png)
---
![web2](https://user-images.githubusercontent.com/33192611/78953841-b08bd700-7b0c-11ea-950a-30967a76c226.png)
##### 控制台输出
---
![cmd](https://user-images.githubusercontent.com/33192611/78953869-d0bb9600-7b0c-11ea-9d23-c9c8671211e7.png)
##### 文本输出结果
---
![sum](https://user-images.githubusercontent.com/33192611/78953879-db762b00-7b0c-11ea-93eb-61a65292cf03.png)

**Comment by congyewang** [comment]
> 我知道了
> 我尝试在xpath后面添加了个print把title，ans_sum，curr都print了出来
> 发现是可以正常爬取的
> 
> ```
> try:
>             for i in range(len(html.xpath('/html/body/div[3]/div[2]/div[4]/div'))):
>                 title.append(html.xpath(
>                     f"/html/body/div[@id='cc-main']/div[2]/div[4]/div[@class='view-quiz-row'][{i + 1}]/div[@class='row-center']/div[@class='topic-options']/div[1]/div[@class='view-quiz-subject']/div[3]//pre[@class='color-33 topic-subject']/text()"))
>                 ans = []
>                 for j in range(len(html.xpath(f"/html/body/div[@id='cc-main']/div[2]/div[4]/div[@class='view-quiz-row'][{i + 1}]/div[@class='row-center']/div[@class='topic-options']/div[@class='view-topic-options']/div[@class='option-content']"))):
>                     ans.append(html.xpath(
>                         f"/html/body/div[@id='cc-main']/div[2]/div[4]/div[@class='view-quiz-row'][{i + 1}]/div[@class='row-center']/div[@class='topic-options']/div[@class='view-topic-options']/div[@class='option-content'][{j + 1}]//span[@class='person-result-answer']/text()"))
>                 ans_sum.append(ans)
>                 curr.append(html.xpath(
>                     f"/html/body/div[@id='cc-main']/div[2]/div[4]/div[@class='view-quiz-row'][{i + 1}]/div[@class='true-rate']/div[1]/div[@class='answer-box'][1]//span/text()"))
>         except Exception:
>             pass
>         print(title)
>         print(ans_sum)
>         print(curr)
>         return title, ans_sum, curr
> ```
> 
> 我们老师喜欢在题目里面加( )
> 在控制台中输出的空格就全部都转换为`\xa0`了
> 可能原因出在这里吧

您好，`\xa0`是不间断空白符 `&nbsp;`，这个Bug我需要进行测试，感谢您的反馈。
