### ISSUE TITLE
请问爬下来的题目不全 还是只能趴已结束的题目?

### ISSUE THREAD

**Issue by lgl1227** [congyewang/Lanmoyun_download#6]
![image](https://user-images.githubusercontent.com/55053750/79960542-19cdfb80-84b8-11ea-9e43-ed121265fa4a.png)
就是这个期中样例爬不下来

**Comment by congyewang** [comment]
> 就是这个期中样例爬不下来

与“已结束”和“进行中”无关，取决于老师是否放开“查看答案”的权限。请查看您的课程是否支持`https://www.mosoteach.cn/web/index.php?c=interaction_quiz&m=person_quiz_result&clazz_course_id=<TYPE_YOUR_CLAZZ_COURSE>&id=<TYPE_YOUR_ID>&order_item=group&user_id=<TYPE_YOUR_USER_ID>`

**Comment by lgl1227** [comment]
那个期中测试老师已经放开权限 ，可是并没有爬到，课程是支持的

**Comment by congyewang** [comment]
> 那个期中测试老师已经放开权限 ，可是并没有爬到，课程是支持的

由于测试时并没有复现出此类问题，请提交**具体环境**与**错误代码**信息，或对照README.md查看是否有相关问题。

**Comment by lgl1227** [comment]
测试环境Win10 64专业版 + Pycharm  修改了代码中的 Cookies
![image](https://user-images.githubusercontent.com/55053750/79988808-aa6d0180-84e1-11ea-9e7c-73f4f825d916.png) 
![image](https://user-images.githubusercontent.com/55053750/79988900-ca042a00-84e1-11ea-80d7-d063d6476b0c.png)
仅仅修改了 setting.py文件 和 start.py文件中的 User-Agent和Cookies信息，我未修改这些信息之前
爬取的Sum.txt文件信息并没有太大的区别
结果：
![image](https://user-images.githubusercontent.com/55053750/79989177-25361c80-84e2-11ea-9c92-10c811692218.png)
![image](https://user-images.githubusercontent.com/55053750/79989267-3c750a00-84e2-11ea-9a3f-2c23331fc336.png)
![image](https://user-images.githubusercontent.com/55053750/79989393-5f072300-84e2-11ea-907b-5bec2a39da98.png)

**Comment by congyewang** [comment]
> 测试环境Win10 64专业版 + Pycharm 修改了代码中的 Cookies

您好，请问*期中测试选择题-样例*班课中有什么与其他班课不同的地方？请使用**开发者工具**对Xpath进行比对。

或修改`./Lanmoyun_scrapy/Lanmoyun_scrapy/spiders/Lanmoyun_spider.py`文件中`start_urls`参数，填写为您报错班课网址，然后返回项目根目录，运行`scrapy crawl Lanmoyun_scrapy`，查看输出内容与报错信息。

**Comment by lgl1227** [comment]
好的 感谢您的指导，我会去查看的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Congye Wang"<notifications@github.com&gt;; 
发送时间: 2020年4月22日(星期三) 晚上10:27
收件人: "congyewang/Lanmoyun_download"<Lanmoyun_download@noreply.github.com&gt;; 
抄送: "乜许、沒資格"<1227404395@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [congyewang/Lanmoyun_download] 请问爬下来的题目不全 还是只能趴已结束的题目? (#6)





  
测试环境Win10 64专业版 + Pycharm 修改了代码中的 Cookies
  
您好，请问期中测试选择题-样例班课中有什么与其他班课不同的地方？请使用开发者工具对Xpath进行比对。
 
或修改./Lanmoyun_scrapy/Lanmoyun_scrapy/spiders/Lanmoyun_spider.py文件中start_urls参数，填写为您报错班课网址，然后返回项目根目录，运行scrapy crawl Lanmoyun_scrapy，查看输出内容与报错信息。
